/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine2;

/**
 *
 * @author Saragih
 * ukuran icon 40x60
 * 
 */
public class VM extends javax.swing.JFrame {

    /**
     * Creates new form VM
     */
    public VM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sprite = new javax.swing.JButton();
        btn_coca = new javax.swing.JButton();
        btn_fanta = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_tebs = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_minute = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_money = new java.awt.TextField();
        btn_insertmoney = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        lbl_money = new java.awt.Label();
        icon_sprite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sprite.setText("Sprite");
        btn_sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_spriteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, -1));

        btn_coca.setText("Coca Cola");
        getContentPane().add(btn_coca, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 164, -1, -1));

        btn_fanta.setText("Fanta");
        getContentPane().add(btn_fanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        btn_tebs.setText("Tebs");
        getContentPane().add(btn_tebs, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jButton6.setText("jButton6");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btn_minute.setText("Minute Maid");
        getContentPane().add(btn_minute, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 223, -1, -1));

        jButton8.setText("jButton8");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jButton9.setText("jButton9");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_insertmoney.setLabel("insert money");
        btn_insertmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertmoneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(txt_money, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_insertmoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_insertmoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 220, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        label1.setText("ON SALE");

        lbl_money.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_money, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 220, -1));

        icon_sprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sprite-logo-vector.png"))); // NOI18N
        getContentPane().add(icon_sprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        setSize(new java.awt.Dimension(690, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertmoneyActionPerformed
        // masukkin uang
        
        int money = 0;
        
        
        money = money + Integer.parseInt(txt_money.getText()) + Integer.parseInt(lbl_money.getText());
        
        lbl_money.setText(Integer.toString(money));
    }//GEN-LAST:event_btn_insertmoneyActionPerformed

    private void btn_spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_spriteActionPerformed
        // Jika ditekan tombol sprite
        int money = 0;
        
        money = Integer.parseInt(lbl_money.getText()) - 5000;
        
        lbl_money.setText(Integer.toString(money));
    }//GEN-LAST:event_btn_spriteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_coca;
    private javax.swing.JButton btn_fanta;
    private java.awt.Button btn_insertmoney;
    private javax.swing.JButton btn_minute;
    private javax.swing.JButton btn_sprite;
    private javax.swing.JButton btn_tebs;
    private javax.swing.JLabel icon_sprite;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label lbl_money;
    private java.awt.TextField txt_money;
    // End of variables declaration//GEN-END:variables
}
