/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Saragih
 */
public class VMSetUp extends javax.swing.JFrame {
    
    
    private void initMoneyStat() throws IOException {
        String record;

        File db = new File("money.txt");
        BufferedReader br = new BufferedReader(new FileReader(db));

        while ((record = br.readLine()) != null) {

            StringTokenizer st = new StringTokenizer(record, ",");


            txt_tMoney.setText(st.nextToken());
            txt_tSheet.setText(st.nextToken()+ " Lembar");
            txt_5K.setText(st.nextToken()+" Lembar");
            txt_10K.setText(st.nextToken()+" Lembar");
            txt_20K.setText(st.nextToken()+" Lembar");
            txt_50K.setText(st.nextToken()+" Lembar");

        }
        br.close();

    }


  
    /**
     * Creates new form VMSetUp
     */
    public VMSetUp() {
        initComponents();
        try {
            initMoneyStat();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_totalMoney = new javax.swing.JLabel();
        lbl_totalSheet = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_20K = new javax.swing.JTextField();
        txt_tMoney = new javax.swing.JTextField();
        txt_tSheet = new javax.swing.JTextField();
        txt_5K = new javax.swing.JTextField();
        txt_10K = new javax.swing.JTextField();
        txt_50K = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_totalSheet1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_totalMoney1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_totalMoney2 = new javax.swing.JLabel();
        lbl_totalMoney3 = new javax.swing.JLabel();
        lbl_totalMoney4 = new javax.swing.JLabel();
        lbl_totalMoney5 = new javax.swing.JLabel();
        lbl_totalMoney6 = new javax.swing.JLabel();
        lbl_totalMoney7 = new javax.swing.JLabel();
        lbl_totalMoney8 = new javax.swing.JLabel();
        lbl_totalMoney9 = new javax.swing.JLabel();
        lbl_totalMoney10 = new javax.swing.JLabel();
        lbl_totalMoney11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inside Vending Machine");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Money Stats"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_totalMoney.setText("Total Money :");
        jPanel1.add(lbl_totalMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 25, -1, -1));

        lbl_totalSheet.setText("Total Sheet :");
        jPanel1.add(lbl_totalSheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, -1, -1));

        jLabel1.setText("Rp 50.000 :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 145, -1, -1));

        jLabel2.setText("Rp 5.000 :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 75, -1, -1));

        jLabel3.setText("Rp 10.000 :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 100, -1, -1));

        jLabel4.setText("Rp 20.000 :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 125, -1, -1));

        txt_20K.setEditable(false);
        txt_20K.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel1.add(txt_20K, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 90, 25));

        txt_tMoney.setEditable(false);
        txt_tMoney.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel1.add(txt_tMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, 25));

        txt_tSheet.setEditable(false);
        txt_tSheet.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel1.add(txt_tSheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, 90, 25));

        txt_5K.setEditable(false);
        txt_5K.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel1.add(txt_5K, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 25));

        txt_10K.setEditable(false);
        txt_10K.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel1.add(txt_10K, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 95, 90, 25));

        txt_50K.setEditable(false);
        txt_50K.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel1.add(txt_50K, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 145, 90, 25));

        jButton1.setText("Retrieve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 280, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Product Remaining"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_totalSheet1.setText("Aquarius :");
        jPanel2.add(lbl_totalSheet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel8.setText("Ciel : ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setText("Coca Cola :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lbl_totalMoney1.setText("0");
        jPanel2.add(lbl_totalMoney1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel6.setText("AW :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel7.setText("Tebs");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel9.setText("Minute Maid :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel10.setText("Fanta");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel11.setText("Burn :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel12.setText("Friesca");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        lbl_totalMoney2.setText("Sprite  :");
        jPanel2.add(lbl_totalMoney2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbl_totalMoney3.setText("0");
        jPanel2.add(lbl_totalMoney3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lbl_totalMoney4.setText("0");
        jPanel2.add(lbl_totalMoney4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        lbl_totalMoney5.setText("0");
        jPanel2.add(lbl_totalMoney5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        lbl_totalMoney6.setText("0");
        jPanel2.add(lbl_totalMoney6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        lbl_totalMoney7.setText("0");
        jPanel2.add(lbl_totalMoney7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        lbl_totalMoney8.setText("0");
        jPanel2.add(lbl_totalMoney8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        lbl_totalMoney9.setText("0");
        jPanel2.add(lbl_totalMoney9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        lbl_totalMoney10.setText("0");
        jPanel2.add(lbl_totalMoney10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        lbl_totalMoney11.setText("0");
        jPanel2.add(lbl_totalMoney11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("add");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setIconTextGap(0);
        jButton3.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 64, 18));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("add");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        jButton4.setIconTextGap(0);
        jButton4.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 64, 18));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("add");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.setBorderPainted(false);
        jButton5.setFocusPainted(false);
        jButton5.setIconTextGap(0);
        jButton5.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 64, 18));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("add");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jButton6.setIconTextGap(0);
        jButton6.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 64, 18));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setText("add");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.setBorderPainted(false);
        jButton7.setFocusPainted(false);
        jButton7.setIconTextGap(0);
        jButton7.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 64, 18));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setText("add");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.setBorderPainted(false);
        jButton8.setFocusPainted(false);
        jButton8.setIconTextGap(0);
        jButton8.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 64, 18));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setText("add");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton9.setBorderPainted(false);
        jButton9.setFocusPainted(false);
        jButton9.setIconTextGap(0);
        jButton9.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 64, 18));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setText("add");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton10.setBorderPainted(false);
        jButton10.setFocusPainted(false);
        jButton10.setIconTextGap(0);
        jButton10.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 64, 18));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setText("add");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton11.setBorderPainted(false);
        jButton11.setFocusPainted(false);
        jButton11.setIconTextGap(0);
        jButton11.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 64, 18));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setText("add");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton12.setBorderPainted(false);
        jButton12.setFocusPainted(false);
        jButton12.setIconTextGap(0);
        jButton12.setMargin(new java.awt.Insets(0, 14, 0, 14));
        jButton12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 64, 18));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 280, 240));

        jButton2.setText("Lock VM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, -1));

        setSize(new java.awt.Dimension(439, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Close Inside Vending Machine
        // Back To the Vending Machine Form
        this.setVisible(false);
        new VM().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Ambil seluruh uang nya sehingga semua kembali menjadi 0
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMSetUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_totalMoney;
    private javax.swing.JLabel lbl_totalMoney1;
    private javax.swing.JLabel lbl_totalMoney10;
    private javax.swing.JLabel lbl_totalMoney11;
    private javax.swing.JLabel lbl_totalMoney2;
    private javax.swing.JLabel lbl_totalMoney3;
    private javax.swing.JLabel lbl_totalMoney4;
    private javax.swing.JLabel lbl_totalMoney5;
    private javax.swing.JLabel lbl_totalMoney6;
    private javax.swing.JLabel lbl_totalMoney7;
    private javax.swing.JLabel lbl_totalMoney8;
    private javax.swing.JLabel lbl_totalMoney9;
    private javax.swing.JLabel lbl_totalSheet;
    private javax.swing.JLabel lbl_totalSheet1;
    private javax.swing.JTextField txt_10K;
    private javax.swing.JTextField txt_20K;
    private javax.swing.JTextField txt_50K;
    private javax.swing.JTextField txt_5K;
    private javax.swing.JTextField txt_tMoney;
    private javax.swing.JTextField txt_tSheet;
    // End of variables declaration//GEN-END:variables
}
