package vendingmachine;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Saragih
 */
public class VM extends javax.swing.JFrame {

    /**
     * Creates new form VM
     */
    public VM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        spriteRB = new javax.swing.JRadioButton();
        cokeRB = new javax.swing.JRadioButton();
        waterRB = new javax.swing.JRadioButton();
        lemonadeRB = new javax.swing.JRadioButton();
        rootbeerRB = new javax.swing.JRadioButton();
        pepsiRB = new javax.swing.JRadioButton();
        purchaseBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moneyTF = new javax.swing.JTextField();
        changeTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine 1.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Vending Machine ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 346, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select an Item"));

        spriteRB.setText("Sprite $ 1.25");
        spriteRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteRBActionPerformed(evt);
            }
        });

        cokeRB.setText("Coke $1.25");
        cokeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeRBActionPerformed(evt);
            }
        });

        waterRB.setText("Water$1.00");
        waterRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterRBActionPerformed(evt);
            }
        });

        lemonadeRB.setText("Lemonade $2.00");
        lemonadeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonadeRBActionPerformed(evt);
            }
        });

        rootbeerRB.setText("Root Beer $1.25");
        rootbeerRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootbeerRBActionPerformed(evt);
            }
        });

        pepsiRB.setText("Pepsi $1.50");
        pepsiRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spriteRB)
                    .addComponent(cokeRB))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waterRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(rootbeerRB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pepsiRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lemonadeRB))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spriteRB)
                    .addComponent(lemonadeRB)
                    .addComponent(pepsiRB))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeRB)
                    .addComponent(waterRB)
                    .addComponent(rootbeerRB))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        purchaseBtn.setText("Purchase");
        purchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(purchaseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jLabel2.setText("Insert Money :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel3.setText("Change :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));
        getContentPane().add(moneyTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 100, -1));

        changeTF.setEditable(false);
        getContentPane().add(changeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 100, -1));

        setSize(new java.awt.Dimension(549, 403));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pepsiRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiRBActionPerformed
        // changing radio buttons to select only one

        if (pepsiRB.isSelected()) {
            cokeRB.setSelected(false);
            lemonadeRB.setSelected(false);
            spriteRB.setSelected(false);
            rootbeerRB.setSelected(false);
            waterRB.setSelected(false);
        }
    }//GEN-LAST:event_pepsiRBActionPerformed


    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        //cancel selection

        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        //clears all selections and textfield
        spriteRB.setSelected(false);
        cokeRB.setSelected(false);
        lemonadeRB.setSelected(false);
        pepsiRB.setSelected(false);
        rootbeerRB.setSelected(false);
        waterRB.setSelected(false);
        moneyTF.setText(""); //null
        changeTF.setText(""); //null


    }//GEN-LAST:event_clearBtnActionPerformed

    private void spriteRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteRBActionPerformed
        // changing radio buttons to select only one

        if (spriteRB.isSelected()) {
            cokeRB.setSelected(false);
            lemonadeRB.setSelected(false);
            pepsiRB.setSelected(false);
            rootbeerRB.setSelected(false);
            waterRB.setSelected(false);
        }
    }//GEN-LAST:event_spriteRBActionPerformed

    private void cokeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeRBActionPerformed
        // changing radio buttons to select only one

        if (cokeRB.isSelected()) {
            pepsiRB.setSelected(false);
            lemonadeRB.setSelected(false);
            spriteRB.setSelected(false);
            rootbeerRB.setSelected(false);
            waterRB.setSelected(false);
        }
    }//GEN-LAST:event_cokeRBActionPerformed

    private void waterRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterRBActionPerformed
        // changing radio buttons to select only one

        if (waterRB.isSelected()) {
            cokeRB.setSelected(false);
            lemonadeRB.setSelected(false);
            spriteRB.setSelected(false);
            rootbeerRB.setSelected(false);
            pepsiRB.setSelected(false);
        }
    }//GEN-LAST:event_waterRBActionPerformed

    private void lemonadeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonadeRBActionPerformed
        // changing radio buttons to select only one

        if (lemonadeRB.isSelected()) {
            cokeRB.setSelected(false);
            pepsiRB.setSelected(false);
            spriteRB.setSelected(false);
            rootbeerRB.setSelected(false);
            waterRB.setSelected(false);
        }
    }//GEN-LAST:event_lemonadeRBActionPerformed

    private void rootbeerRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootbeerRBActionPerformed
        // changing radio buttons to select only one

        if (rootbeerRB.isSelected()) {
            cokeRB.setSelected(false);
            lemonadeRB.setSelected(false);
            spriteRB.setSelected(false);
            pepsiRB.setSelected(false);
            waterRB.setSelected(false);
        }
    }//GEN-LAST:event_rootbeerRBActionPerformed

    private void purchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseBtnActionPerformed
        // this pays for our purchase if we have enough money 

        double money = 0;

        money = Double.parseDouble(moneyTF.getText());

        if (spriteRB.isSelected()) {
            money = money - 1.25;
        } else if (cokeRB.isSelected()) {
            money = money - 1.25;
        } else if (lemonadeRB.isSelected()) {
            money = money - 2.00;
        } else if (pepsiRB.isSelected()) {
            money = money - 1.50;
        } else if (waterRB.isSelected()) {
            money = money - 1.00;
        } else if (rootbeerRB.isSelected()) {
            money = money - 1.25;
        }
        
        if (money < 0){
            JOptionPane.showMessageDialog(rootPane, "Sory You Do Not Have Enough Money");
        } else{
            changeTF.setText(Double.toString(money));
        }
    }//GEN-LAST:event_purchaseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField changeTF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JRadioButton cokeRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton lemonadeRB;
    private javax.swing.JTextField moneyTF;
    private javax.swing.JRadioButton pepsiRB;
    private javax.swing.JButton purchaseBtn;
    private javax.swing.JRadioButton rootbeerRB;
    private javax.swing.JRadioButton spriteRB;
    private javax.swing.JRadioButton waterRB;
    // End of variables declaration//GEN-END:variables
}
